spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticker
    username: postgres
    password: postgres
    pool-size: 30
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


#spring:
#  flyway:
#    baseline-on-migrate: true
kraken:
  ticker:
    baseUrl: https://api.kraken.com/0/public/Ticker?pair=
    pairs: xbtusd,xbteur
scheduled:
  task:
    job: 0/5 * * ? * *